fix: add missing recording field to Config test initializer
Add RecordingConfig::default() to create_menu_test_config after rebase on main which introduced recording field.

Fixes compilation error: missing field `recording` in initializer of `config::Config`

Signed-off-by: Marcin Skalski <skalskimarcin33@gmail.com>